/* ==========================================
   Kamus Bahasa (Dikelompokkan)
========================================== */

export default {
  /* ---------- Login Screen ---------- */
  "auth.login_failed_credential": "Login failed. Incorrect ID/Email or password.",
  "auth.login_btn": "Log In",
  "auth.forgot_password": "Forgot Password?",
  "auth.nim_email_required": "Student ID or Email is required",
  "auth.nim_email_label": "AstraTech Student ID or Email",
  "auth.nim_email_placeholder": "Student ID / AstraTech Email",
  "auth.password_placeholder": "Enter password",
  "auth.no_account": "Don't have an account?",

  /* ---------- Register Screen ---------- */
  "auth.name_required": "Full name is required",
  "auth.name_max": "Name max 100 characters",
  "auth.study_program_required": "Study program is required",
  "auth.phone_required": "Phone number is required",
  "auth.phone_max": "Phone number max 15 characters",
  "auth.register_success": "Registration Successful! Please log in.",
  "auth.register_success_title": "Registration Successful!",
  "auth.register_success_desc": "Your account has been successfully created. Please log in to start shopping.",
  "auth.continue_login_btn": "Continue to Login",
  "auth.toast_password_updated": "Password updated successfully!",
  "auth.toast_password_updated_desc": "Your password has been successfully changed. Please log in with your new password.",
  "auth.register_failed": "Registration failed",
  "auth.step_account": "Account",
  "auth.step_profile": "Profile",
  "auth.step_otp": "OTP",
  "auth.step_password": "Password",
  "auth.name_label": "Full Name",
  "auth.name_placeholder": "Enter your full name",
  "auth.study_program_label": "Study Program",
  "auth.study_program_placeholder": "Select Study Program",
  "auth.phone_label": "Phone Number",
  "auth.phone_placeholder": "e.g., 08123456789 or +628123456789",
  "auth.otp_label": "OTP Code (6 Digits)",
  "auth.new_password_label": "New Password",
  "auth.confirm_password_label": "Confirm Password",
  "auth.study_program_title": "Select Study Program",
  "auth.search_study_program": "Search study program...",
  "auth.nim_required": "Student ID is required",
  "auth.nim_max": "Student ID max 15 characters",
  "auth.email_required": "AstraTech Email is required",
  "auth.email_format_error": "Email format must be [ID]@polytechnic.astra.ac.id",
  "auth.email_max": "Email max 100 characters",
  "auth.password_min": "Password minimum 8 characters",
  "auth.nim_label": "Student ID",
  "auth.nim_placeholder": "Enter your Student ID",
  "auth.email_label": "AstraTech Email",
  "auth.email_placeholder": "e.g., id@polytechnic.astra.ac.id",
  "auth.next_btn": "Next",
  "auth.back_btn": "Back",
  "auth.have_account": "Already have an account?",

  /* ---------- Forgot Password Screen ---------- */
  "auth.otp_placeholder": "Enter 6 digit code",
  "auth.send_otp_btn": "Send OTP",
  "auth.toast_otp_verify_success": "OTP verification successful!",
  "auth.toast_otp_verify_failed": "Incorrect or expired OTP code",
  "auth.cancel_btn": "Cancel",
  "auth.nim_email_placeholder2": "Enter Student ID / Email",
  "auth.confirm_password_placeholder": "Repeat new password",
  "auth.verify_btn": "Verify",
  "auth.update_password_btn": "Update Password",
  "auth.remember_password": "Remember your password?",
  "auth.toast_email_not_found": "Email/ID is not registered",
  "auth.toast_password_update_failed": "Failed to reset password",

  /* ---------- Auth Umum ---------- */
  "auth.register_now": "Register Now",
  "auth.password_required": "Password is required",
  "auth.server_error": "Failed to connect to backend server.",
  "auth.password_label": "Password",
  "auth.or": "or",
  "auth.toast_otp_success": "OTP code sent successfully!",
  "auth.login_now": "Log In Now",
  "auth.password_min_placeholder": "Minimum 8 characters",
  "auth.toast_server_error": "Failed to contact backend server.",
  "auth.toast_new_password_required": "New password is required",
  "auth.toast_password_mismatch": "Password confirmation does not match",

  /* ---------- Study Programs ---------- */
  "prodi.konstruksi_gedung": "Building Construction Technology",
  "prodi.manajemen_informatika": "Informatics Management",
  "prodi.mekatronika": "Mechatronics",
  "prodi.mesin_otomotif": "Automotive Engineering",
  "prodi.perkakas_produksi": "Production Tooling and Equipment Manufacture",
  "prodi.proses_manufaktur": "Manufacturing Process and Production Engineering",
  "prodi.tr_alat_berat": "Heavy Equipment Maintenance Engineering Technology",
  "prodi.tr_logistik": "Logistics Engineering Technology",
  "prodi.tr_rpl": "Software Engineering Technology",

  /* ---------- Home Screen ---------- */
  "home.empty_recommended_desc": "There are no recommended items from other users at this moment.",
  "home.empty_recommended_title": "No Recommendations Yet",
  "home.filter_all": "All",
  "home.filter_cheap": "Cheapest",
  "home.filter_good": "Best Condition",
  "home.filter_near": "Nearest",
  "home.loc_denied_msg": "Location permission is disabled in your device Settings. Please enable location access in Device Settings.",
  "home.loc_denied_title": "Location Access Denied",
  "home.loc_perm_msg": "The app needs location access to display products and COD spots near you. Continue?",
  "home.loc_perm_title": "Location Access Permission",
  "home.recommended": "Recommended for You",
  "home.title_cheap": "Cheapest Price",
  "home.title_good": "Best Selection",
  "home.title_near": "Nearest to You",

  /* ---------- Search Screen ---------- */
  "search.all_categories": "All",
  "search.categories": "Categories",
  "search.cond_all": "All",
  "search.condition": "Item Condition",
  "search.empty_desc": "Try using different keywords or select a different category.",
  "search.empty_title": "Items Not Found",
  "search.placeholder": "Search items here...",
  "search.price_range": "Price Range",
  "search.results": "Search Results",

  /* ---------- Cart Screen ---------- */
  "cart.arrange_cod": "Arranging a COD meeting with:",
  "cart.checkout_btn": "Checkout COD",
  "cart.confirm_title": "Arrange COD Meeting",
  "cart.empty_desc": "No items have been added to your shopping cart yet.",
  "cart.empty_title": "Your Cart is Empty",
  "cart.note_label": "Note:",
  "cart.note_placeholder": "Write note here...",
  "cart.remove_confirm_msg": "Are you sure you want to remove this item from your cart?",
  "cart.remove_confirm_title": "Remove Item",
  "cart.seller_label": "Seller",
  "cart.submit_cod": "Arrange & Contact WA",
  "cart.success_toast": "COD booking created successfully.",
  "cart.title": "Shopping Cart",
  "cart.total": "Total:",

  /* ---------- Transaction History Screen ---------- */
  "history.btn_accept": "Accept",
  "history.btn_cancel": "Cancel",
  "history.btn_complete": "Done COD",
  "history.btn_reject": "Reject",
  "history.btn_wa": "WhatsApp",
  "history.buyer_label": "Buyer:",
  "history.cancel_msg": "Are you sure you want to cancel this booking?",
  "history.cancel_title": "Cancel Booking",
  "history.cod_notes": "COD Notes",
  "history.complete_msg": "Are you stating that COD succeeded and transaction is complete?",
  "history.complete_title": "Complete Transaction",
  "history.empty_desc": "Your transaction history for this status is empty.",
  "history.empty_title": "No Transactions",
  "history.no_phone": "Phone number is not available.",
  "history.not_found": "Transaction not found.",
  "history.notif_accepted_msg": "You have accepted this COD order.",
  "history.notif_accepted_title": "Order Accepted",
  "history.notif_cancelled_msg": "The COD order has been cancelled.",
  "history.notif_cancelled_title": "Order Cancelled",
  "history.notif_completed_msg": "The COD transaction has been marked as complete.",
  "history.notif_completed_title": "Transaction Completed",
  "history.notif_rejected_msg": "You have rejected this COD order.",
  "history.notif_rejected_title": "Order Rejected",
  "history.notif_update_msg": "Transaction status updated successfully.",
  "history.notif_update_title": "Transaction Update",
  "history.seller_label": "Seller:",
  "history.tab_buyer": "Purchases",
  "history.tab_seller": "Sales",
  "history.title": "Transaction History",
  "history.total_label": "Total:",
  "history.trans_date": "Transaction Date",
  "history.trans_detail_title": "Transaction Details",
  "history.update_fail": "Failed to update transaction",
  "history.wa_fail": "Failed to open WhatsApp.",
  "history.wa_template": "Hello %{name},\nI would like to contact you regarding a COD order on Thriftly:\n\n%{items}\n\n*Total:* %{total}\nHow should we proceed with the COD?",
  "history.yes_cancel": "Yes, Cancel",
  "history.yes_complete": "Yes, Complete",

  /* ---------- My Items Screen ---------- */
  "myitems.btn_delete": "Delete",
  "myitems.delete_confirm": "Are you sure you want to delete {count} selected items?",
  "myitems.delete_fail": "Failed to delete some items",
  "myitems.delete_success": "{count} items deleted successfully",
  "myitems.delete_title": "Delete Items",
  "myitems.deselect_all": "Deselect All",
  "myitems.empty_search": "No items matched your search.",
  "myitems.empty_state": "No items match your current filters or status.",
  "myitems.empty_title": "No Items Found",
  "myitems.error_price": "Minimum limit cannot exceed maximum.",
  "myitems.item_status": "Item Status",
  "myitems.select_all": "Select All",
  "myitems.selected": "selected",
  "myitems.sort_time": "Sort by Time",
  "myitems.start_selling": "Start Selling",
  "myitems.tab_all": "All",
  "myitems.tab_available": "Available",
  "myitems.tab_booked": "Booked",
  "myitems.tab_sold": "Sold",
  "myitems.title": "My Items",

  /* ---------- Post Item Screen ---------- */
  "postitem.back_to_detail": "Back to Item Details",
  "postitem.cancel": "Cancel",
  "postitem.category_label": "Category",
  "postitem.check_desc": "Failed points must be given a note.",
  "postitem.check_done_desc": "You have answered all {count} points.",
  "postitem.check_done_title": "Check Sheet Completed!",
  "postitem.check_fail": "Fail",
  "postitem.check_note_ph": "Explain this defect condition...",
  "postitem.check_pass": "Pass",
  "postitem.check_title": "Condition Check Sheet",
  "postitem.checksheet_tab": "Check Sheet",
  "postitem.cond_good": "Good",
  "postitem.cond_poor": "Poor",
  "postitem.cond_vg": "Very Good",
  "postitem.condition_calc": "Calculated automatically from Check Sheet.",
  "postitem.condition_no_cat": "Please select a category first.",
  "postitem.condition_none": "This category does not have a check sheet.",
  "postitem.condition_title": "Item Condition",
  "postitem.cover_badge": "COVER",
  "postitem.description_label": "Item Description",
  "postitem.description_placeholder": "Describe condition, defects, etc...",
  "postitem.detail": "Detail",
  "postitem.edit_title": "Edit Item",
  "postitem.err_out_of_bounds": "The meeting location must be within the Astra Polytechnic campus area.",
  "postitem.fetching_location": "Locating Campus Area...",
  "postitem.fill_checksheet": "Fill In",
  "postitem.get_location": "Select Campus COD Meeting Spot",
  "postitem.location_detail_label": "Location Details",
  "postitem.location_detail_placeholder": "E.g., Lobby Building B",
  "postitem.location_subtitle": "Determine meeting point",
  "postitem.location_title": "Meeting Location",
  "postitem.map_coord_label": "Campus COD Meeting Spot",
  "postitem.media": "Media",
  "postitem.name_label": "Item Name",
  "postitem.name_placeholder": "E.g., Astra Jacket",
  "postitem.photo_subtitle": "Upload up to 5 photos",
  "postitem.photo_title": "Item Photos",
  "postitem.points_answered": "points answered",
  "postitem.points_passed": "points passed",
  "postitem.points_passed_label": "Passed",
  "postitem.post": "Add",
  "postitem.price_label": "Price",
  "postitem.recorded_as": "This item's condition will be recorded as",
  "postitem.save_btn": "Save Changes",
  "postitem.select_category": "Select Category",
  "postitem.select_spot_modal_title": "Select COD Meeting Spot",
  "postitem.spot_set_toast": "COD spot set to:",
  "postitem.spot_verified": "Verified Campus Spot",
  "postitem.title": "Add Item",
  "postitem.upload_desc": "Choose image from gallery or camera.\nJPG, JPEG, PNG. Max 5 MB.",
  "postitem.upload_photo": "Upload Photo",
  "postitem.use_gps": "Use Current Device GPS Location",

  /* ---------- Detail Screen ---------- */
  "detail.checksheet_failed_count": "There are {count} minus notes from the seller",
  "detail.checksheet_title": "Physical Condition (Check Sheet)",
  "detail.contact_wa": "Contact via WA",
  "detail.delete_btn": "Delete",
  "detail.delete_msg": "Are you sure you want to permanently delete this item from Thriftly?",
  "detail.delete_title": "Delete Item?",
  "detail.description": "Description",
  "detail.edit_item": "Edit Item",
  "detail.hide_checks": "Hide Checks",
  "detail.login_required_contact": "Please log in first to contact the seller.",
  "detail.login_to_save": "You must log in to save items to your shopping cart",
  "detail.meeting_location": "Meeting Location",
  "detail.no_wa": "Seller WA number is not available.",
  "detail.not_available": "This item is no longer available for booking.",
  "detail.open_wa_err": "Failed to open WhatsApp.",
  "detail.seller": "Seller",
  "detail.view_checks": "View All Checks",

  /* ---------- Checksheet ---------- */
  "checksheet.c01_01": "Screen is intact (no cracks or dead pixels)",
  "checksheet.c01_02": "Battery can be charged normally",
  "checksheet.c01_03": "All physical buttons / keyboard / touch screen are responsive",
  "checksheet.c01_04": "Speaker and microphone (audio) function normally",
  "checksheet.c01_05": "Connection ports (USB, charger, HDMI, etc.) work well",
  "checksheet.c01_06": "No physical damage to the body (cracks/severe dents)",
  "checksheet.c01_07": "Device can turn on and operate normally (no bootloop/completely dead)",
  "checksheet.c01_08": "Charger / cable accessories are available as described",
  "checksheet.c02_01": "All pages are intact and complete (none torn/missing)",
  "checksheet.c02_02": "Front and back covers are still attached well",
  "checksheet.c02_03": "Binding is still strong (not loose)",
  "checksheet.c02_04": "No excessive scribbles covering the main text",
  "checksheet.c02_05": "Pages are not moldy, wet, or severely musty",
  "checksheet.c02_06": "Print/text quality is still clearly readable",
  "checksheet.c03_01": "Item is not expired (for ink/paint/markers)",
  "checksheet.c03_02": "Main functions work well (pen writes, calculator turns on, etc.)",
  "checksheet.c03_03": "No broken or missing parts that interfere with function",
  "checksheet.c03_04": "Physical condition is still clean and usable",
  "checksheet.c04_01": "No noticeable permanent stains",
  "checksheet.c04_02": "No tears, holes, or loose stitches",
  "checksheet.c04_03": "Color has not faded significantly",
  "checksheet.c04_04": "Zippers, buttons, or other fasteners function normally",
  "checksheet.c04_05": "Size label/tag is still clearly readable",
  "checksheet.c04_06": "No hard-to-remove odors (already washed clean)",
  "checksheet.c05_01": "Components or tools are intact, nothing is broken/cracked (especially glass)",
  "checksheet.c05_02": "All parts/accessories are complete according to description",
  "checksheet.c05_03": "Measuring scale (if any) is still clearly readable",
  "checksheet.c05_04": "Tool functions mechanically/electrically well",
  "checksheet.c05_05": "No rust or chemical contamination damaging the tool",
  "checksheet.c06_01": "No structural damage (broken, bent, severely cracked)",
  "checksheet.c06_02": "Surface has no scratches or dents that impair function",
  "checksheet.c06_03": "Joints/hinges/bolts are still strong and not loose",
  "checksheet.c06_04": "Drawers, doors, or wheels (if any) can move/open smoothly",
  "checksheet.c06_05": "Not moldy, termite-free, and no stubborn stains",
  "checksheet.c07_01": "No structural damage (broken, cracked, bent)",
  "checksheet.c07_02": "All parts are complete according to original completeness",
  "checksheet.c07_03": "Material (fabric, rubber, iron) is still strong and usable",
  "checksheet.c07_04": "No excessive rust that interferes with tool function",
  "checksheet.c07_05": "Functions normally according to its purpose",
  "checksheet.c07_06": "Size/specifications are exactly as stated in the description",

  /* ---------- Profile Screen ---------- */
  "profile.account": "Account",
  "profile.account_center": "Account Center",
  "profile.cancel": "Cancel",
  "profile.desc_account": "Manage profile & security",
  "profile.desc_history": "Purchases & sales",
  "profile.desc_my_items": "Manage item listings",
  "profile.desc_notification": "Alerts & messages",
  "profile.lang_english": "English",
  "profile.lang_indonesia": "Indonesia",
  "profile.language": "Language",
  "profile.logout": "Log Out",
  "profile.logout_confirm_message": "Are you sure you want to log out of your account?",
  "profile.logout_confirm_title": "Confirm Log Out",
  "profile.menu_notification": "Notifications",
  "profile.my_orders": "Transaction History",
  "profile.preferences": "Preferences",
  "profile.saved_items": "My Items",
  "profile.yes_logout": "Yes, Log Out",

  /* ---------- Account Center Screen ---------- */
  "account.campus_identity": "Student Identity",
  "account.cancel": "Cancel",
  "account.change_password": "Change Password",
  "account.change_password_title": "Change Password",
  "account.confirm_password": "Confirm New Password",
  "account.confirm_password_placeholder": "Repeat new password",
  "account.email": "Email",
  "account.full_name": "Full Name",
  "account.name_placeholder": "Enter full name",
  "account.new_password": "New Password",
  "account.new_password_placeholder": "Minimum 8 characters",
  "account.nim": "Student ID",
  "account.old_password": "Current Password",
  "account.old_password_placeholder": "Enter old password",
  "account.phone": "Phone Number",
  "account.phone_placeholder": "e.g., 08123456789 or +628123456789",
  "account.public_info": "Public Information",
  "account.save": "Save",
  "account.save_password": "Save Password",
  "account.title": "Account Center",

  /* ---------- Notification Screen ---------- */
  "notification.delete_confirm": "This action cannot be undone. The %{count} selected notifications will be permanently deleted from your history.",
  "notification.delete_success": "Notifications successfully deleted",
  "notification.delete_title": "Delete Notifications",
  "notification.empty_desc": "You do not have any new notifications at the moment.",
  "notification.empty_title": "No Notifications",
  "notification.mark_all_read": "Mark All as Read",
  "notification.mark_read": "Mark as Read",
  "notification.perm_allow": "Allow",
  "notification.perm_deny": "Deny",
  "notification.perm_msg": "THRIFTLY needs notification access so you won't miss order updates and messages. Continue?",
  "notification.perm_title": "Enable Notifications",
  "notification.title": "Notifications",

  /* ---------- Notification Types ---------- */
  "notif_type.accepted_msg": "%{name} has accepted your COD order. Please contact via WhatsApp.",
  "notif_type.accepted_title": "Order Accepted",
  "notif_type.cancelled_msg": "%{name} has cancelled the COD order.",
  "notif_type.cancelled_title": "Order Cancelled",
  "notif_type.completed_msg": "The COD transaction has been marked as completed.",
  "notif_type.completed_title": "Transaction Completed",
  "notif_type.new_order_msg": "%{name} has requested a new COD order for your product.",
  "notif_type.new_order_title": "New COD Order",
  "notif_type.rejected_msg": "%{name} has rejected your COD order.",
  "notif_type.rejected_title": "Order Rejected",

  /* ---------- Categories ---------- */
  "category.cat01": "Electronics & Gadgets",
  "category.cat02": "Books & Modules",
  "category.cat03": "Stationery & Supplies",
  "category.cat04": "Clothes & Campus Attire",
  "category.cat05": "Practicum & Lab Tools",
  "category.cat06": "Furniture & Dorm Supplies",
  "category.cat07": "Sports & Hobbies",

  /* ---------- API Messages ---------- */
  "api.ERR_AUTH_FAILED": "Authentication failed",
  "api.ERR_BAD_CREDENTIALS": "Incorrect ID/Email or Password",
  "api.ERR_EMAIL_EXISTS": "Email is already in use",
  "api.ERR_EMAIL_FORMAT": "Email must match your Student ID",
  "api.ERR_INVALID_OTP": "Incorrect OTP code",
  "api.ERR_NIM_EXISTS": "Student ID is already registered",
  "api.ERR_OTP_EXPIRED": "OTP code has expired",
  "api.ERR_OUT_OF_BOUNDS": "The meeting location must be within the Astra Polytechnic campus area.",
  "api.ERR_USER_NOT_FOUND": "Student ID or Email is not registered",
  "api.SUCCESS_LOGIN": "Login successful",
  "api.SUCCESS_OTP_SENT": "OTP code sent successfully",
  "api.SUCCESS_OTP_VALID": "OTP code is valid",
  "api.SUCCESS_PASSWORD_RESET": "Password updated successfully",
  "api.SUCCESS_REGISTER": "Registration successful! Please log in.",

  /* ---------- Status Labels ---------- */
  "status.accepted": "COD In Progress",
  "status.available": "Available",
  "status.booked": "Booked",
  "status.cancelled": "Cancelled",
  "status.completed": "Completed",
  "status.pending": "Pending",
  "status.rejected": "Rejected",
  "status.sold": "Sold",

  /* ---------- Navigation ---------- */
  "nav.cart": "Cart",
  "nav.home": "Home",
  "nav.profile": "Profile",
  "nav.search": "Search",

  /* ---------- Common ---------- */
  "common.all": "All",
  "common.allow": "Allow",
  "common.apply_filter": "Apply Filter",
  "common.cancel": "Cancel",
  "common.category": "Category",
  "common.close": "Close",
  "common.delete": "Delete",
  "common.deny": "Deny",
  "common.empty_search_result": "No results found.",
  "common.error": "Failed to save changes",
  "common.filter": "Filter",
  "common.max": "Max",
  "common.min": "Min",
  "common.newest": "Newest",
  "common.oldest": "Oldest",
  "common.read_more": "Read More",
  "common.required": "Required field",
  "common.sort": "Sort",
  "common.success": "Changes saved successfully!",
  "common.yes": "Yes",
  "common.yes_delete": "Yes, Delete",

  /* ---------- Transaction History Screen ---------- */
  "history.update_fail": "Failed to update transaction",
  "history.no_phone": "Phone number is not available.",
  "history.wa_fail": "Failed to open WhatsApp.",
  "history.wa_template": "Hello %{name},\nI would like to contact you regarding a COD order on Thriftly:\n\n%{items}\n\n*Total:* %{total}\nHow should we proceed with the COD?",
  "history.notif_update_title": "Transaction Update",
  "history.notif_update_msg": "Transaction status updated successfully.",
  "history.notif_accepted_title": "Order Accepted",
  "history.notif_accepted_msg": "You have accepted this COD order.",
  "history.notif_rejected_title": "Order Rejected",
  "history.notif_rejected_msg": "You have rejected this COD order.",
  "history.notif_cancelled_title": "Order Cancelled",
  "history.notif_cancelled_msg": "The COD order has been cancelled.",
  "history.notif_completed_title": "Transaction Completed",
  "history.notif_completed_msg": "The COD transaction has been marked as complete.",
  "history.title": "Transaction History",
  "history.tab_buyer": "Purchases",
  "history.tab_seller": "Sales",
  "history.empty_title": "No Transactions",
  "history.empty_desc": "Your transaction history for this status is empty.",
  "history.seller_label": "Seller:",
  "history.buyer_label": "Buyer:",
  "history.total_label": "Total:",
  "history.btn_cancel": "Cancel",
  "history.btn_reject": "Reject",
  "history.btn_accept": "Accept",
  "history.btn_wa": "WhatsApp",
  "history.btn_complete": "Done COD",
  "history.cancel_title": "Cancel Booking",
  "history.cancel_msg": "Are you sure you want to cancel this booking?",
  "history.complete_title": "Complete Transaction",
  "history.complete_msg": "Are you stating that COD succeeded and transaction is complete?",
  "history.yes_cancel": "Yes, Cancel",
  "history.yes_complete": "Yes, Complete",
  "history.trans_date": "Transaction Date",
  "history.trans_detail_title": "Transaction Details",
  "history.not_found": "Transaction not found.",
  "history.cod_notes": "COD Notes",

  /* ---------- Detail Screen ---------- */
  "detail.login_to_save": "You must log in to save items to your shopping cart",
  "detail.contact_wa": "Contact via WA",
  "detail.edit_item": "Edit Item",
  "detail.delete_title": "Delete Item?",
  "detail.delete_msg": "Are you sure you want to permanently delete this item from Thriftly?",
  "detail.delete_btn": "Delete",
  "detail.meeting_location": "Meeting Location",
  "detail.view_checks": "View All Checks",
  "detail.hide_checks": "Hide Checks",
  "detail.description": "Description",
  "detail.seller": "Seller",
  "detail.login_required_contact": "Please log in first to contact the seller.",
  "detail.no_wa": "Seller WA number is not available.",
  "detail.not_available": "This item is no longer available for booking.",
  "detail.checksheet_title": "Physical Condition (Check Sheet)",
  "detail.checksheet_failed_count": "There are {count} minus notes from the seller",
  "detail.open_wa_err": "Failed to open WhatsApp."
};