/* ==========================================
   Kamus Bahasa (Dikelompokkan)
========================================== */

export default {
    /* ---------- Login Screen ---------- */
  "auth.login_failed_credential": "NIM/Email atau Password salah!",
  "auth.login_btn": "Masuk",
  "auth.forgot_password": "Lupa Kata Sandi?",
  "auth.nim_email_required": "NIM atau Email wajib diisi",
  "auth.nim_email_label": "NIM atau Email AstraTech",
  "auth.nim_email_placeholder": "NIM / Email AstraTech",
  "auth.password_placeholder": "Masukkan kata sandi",
  "auth.no_account": "Belum punya akun?",

  /* ---------- Register Screen ---------- */
  "auth.name_required": "Nama lengkap wajib diisi",
  "auth.name_max": "Nama maksimal 100 karakter",
  "auth.study_program_required": "Program studi wajib diisi",
  "auth.phone_required": "Nomor telepon wajib diisi",
  "auth.phone_max": "Nomor telepon maksimal 15 karakter",
  "auth.register_success": "Pendaftaran Berhasil! Silakan masuk.",
  "auth.register_success_title": "Pendaftaran Berhasil!",
  "auth.register_success_desc": "Akun Anda telah berhasil dibuat. Silakan masuk untuk mulai berbelanja.",
  "auth.continue_login_btn": "Lanjut ke Login",
  "auth.toast_password_updated": "Kata sandi berhasil diperbarui!",
  "auth.toast_password_updated_desc": "Kata sandi Anda telah berhasil diubah. Silakan masuk dengan sandi baru Anda.",
  "auth.register_failed": "Gagal melakukan registrasi",
  "api.NIM sudah terdaftar": "NIM atau Email sudah terdaftar!",
  "api.NIM sudah terdaftar!": "NIM atau Email sudah terdaftar!",
  "api.Email sudah terdaftar": "NIM atau Email sudah terdaftar!",
  "api.Email sudah terdaftar!": "NIM atau Email sudah terdaftar!",
  "api.ERR_NIM_EXISTS": "NIM atau Email sudah terdaftar!",
  "api.ERR_EMAIL_EXISTS": "NIM atau Email sudah terdaftar!",
  "api.NIM atau Email sudah terdaftar!": "NIM atau Email sudah terdaftar!",
  "api.ERR_BAD_CREDENTIALS": "NIM/Email atau Password salah!",
  "api.NIM/Email atau Password salah!": "NIM/Email atau Password salah!",
  "api.NIM/Email atau password salah": "NIM/Email atau Password salah!",
  "api.ERR_USER_NOT_FOUND": "NIM atau Email tidak terdaftar!",
  "api.Pengguna tidak ditemukan": "NIM atau Email tidak terdaftar!",
  "auth.step_account": "Akun",
  "auth.step_profile": "Profil",
  "auth.step_otp": "OTP",
  "auth.step_password": "Sandi",
  "auth.name_label": "Nama Lengkap",
  "auth.name_placeholder": "Masukkan nama lengkap Anda",
  "auth.study_program_label": "Program Studi",
  "auth.study_program_placeholder": "Pilih Program Studi",
  "auth.phone_label": "Nomor Telepon",
  "auth.phone_placeholder": "contoh: 08123456789",
  "auth.otp_label": "Kode OTP (6 Digit)",
  "auth.new_password_label": "Kata Sandi Baru",
  "auth.confirm_password_label": "Konfirmasi Kata Sandi",
  "auth.study_program_title": "Pilih Program Studi",
  "auth.search_study_program": "Cari program studi...",
  "auth.nim_required": "NIM wajib diisi",
  "auth.nim_max": "NIM maksimal 15 karakter",
  "auth.email_required": "Email AstraTech wajib diisi",
  "auth.email_format_error": "Format email harus [NIM]@polytechnic.astra.ac.id",
  "auth.email_max": "Email maksimal 100 karakter",
  "auth.password_min": "Kata sandi minimal 8 karakter",
  "auth.nim_label": "NIM",
  "auth.nim_placeholder": "Masukkan NIM Anda",
  "auth.email_label": "Email AstraTech",
  "auth.email_placeholder": "contoh: nim@polytechnic.astra.ac.id",
  "auth.next_btn": "Lanjut",
  "auth.back_btn": "Kembali",
  "auth.have_account": "Sudah punya akun?",

  /* ---------- Forgot Password Screen ---------- */
  "auth.otp_placeholder": "Masukkan 6 digit kode",
  "auth.send_otp_btn": "Kirim OTP",
  "auth.toast_otp_verify_success": "Verifikasi OTP sukses!",
  "auth.toast_otp_verify_failed": "Kode OTP salah atau kedaluwarsa!",
  "api.ERR_INVALID_OTP": "Kode OTP salah atau kedaluwarsa!",
  "api.ERR_OTP_EXPIRED": "Kode OTP salah atau kedaluwarsa!",
  "api.OTP tidak valid": "Kode OTP salah atau kedaluwarsa!",
  "api.OTP sudah kedaluwarsa": "Kode OTP salah atau kedaluwarsa!",
  "auth.cancel_btn": "Batal",
  "auth.nim_email_placeholder2": "Masukkan NIM / Email",
  "auth.confirm_password_placeholder": "Ulangi kata sandi baru",
  "auth.verify_btn": "Verifikasi",
  "auth.update_password_btn": "Perbarui Sandi",
  "auth.remember_password": "Ingat kata sandi Anda?",
  "auth.toast_email_not_found": "NIM atau Email tidak terdaftar!",
  "auth.toast_password_update_failed": "Gagal mengatur ulang kata sandi",
  "auth.toast_password_updated": "Sandi Diperbarui!",
  "auth.toast_password_updated_desc": "Kata sandi Anda telah berhasil diubah. Silakan masuk dengan sandi baru Anda.",
  "auth.continue_login_btn": "Lanjut ke Login",
  "auth.toast_new_password_required": "Kata sandi baru wajib diisi",
  "auth.confirm_password_required": "Konfirmasi kata sandi wajib diisi",
  "auth.toast_password_mismatch": "Konfirmasi kata sandi tidak cocok",
  "auth.nim_email_required": "NIM atau Email wajib diisi",
  "auth.otp_required": "Masukkan 6 digit kode OTP",
  "auth.password_min_length": "Kata sandi minimal 8 karakter",

  /* ---------- Auth Umum ---------- */
  "auth.register_now": "Daftar Sekarang",
  "auth.password_required": "Kata sandi wajib diisi",
  "auth.server_error": "Gagal terhubung ke server Spring Boot Anda.",
  "auth.password_label": "Kata Sandi",
  "auth.or": "atau",
  "auth.toast_otp_success": "Kode OTP berhasil dikirim!",
  "auth.login_now": "Masuk Sekarang",
  "auth.password_min_placeholder": "Minimal 8 karakter",
  "auth.toast_server_error": "Gagal menghubungi server backend.",

  /* ---------- Study Programs ---------- */
  "prodi.konstruksi_gedung": "Teknologi Konstruksi Bangunan Gedung",
  "prodi.manajemen_informatika": "Manajemen Informatika",
  "prodi.mekatronika": "Mekatronika",
  "prodi.mesin_otomotif": "Mesin Otomotif",
  "prodi.perkakas_produksi": "Pembuatan Peralatan dan Perkakas Produksi",
  "prodi.proses_manufaktur": "Teknik Produksi dan Proses Manufaktur",
  "prodi.tr_alat_berat": "Teknologi Rekayasa Pemeliharaan Alat Berat",
  "prodi.tr_logistik": "Teknologi Rekayasa Logistik",
  "prodi.tr_rpl": "Teknologi Rekayasa Perangkat Lunak",

  /* ---------- Home Screen ---------- */
  "home.empty_recommended_desc": "Belum ada rekomendasi barang dari pengguna lain saat ini.",
  "home.empty_recommended_title": "Belum Ada Rekomendasi",
  "home.filter_all": "Semua",
  "home.filter_cheap": "Termurah",
  "home.filter_good": "Terbaik",
  "home.filter_near": "Terdekat",
  "home.loc_denied_msg": "Izin lokasi dinonaktifkan di Pengaturan HP Anda. Silakan izinkan akses lokasi melalui Pengaturan Perangkat.",
  "home.loc_denied_title": "Akses Lokasi Ditolak",
  "home.loc_perm_msg": "Aplikasi membutuhkan akses lokasi Anda untuk menampilkan produk dan tempat COD di sekitar Anda. Lanjutkan?",
  "home.loc_perm_title": "Izin Akses Lokasi",
  "home.recommended": "Rekomendasi Untuk Anda",
  "home.title_cheap": "Harga Termurah",
  "home.title_good": "Pilihan Terbaik",
  "home.title_near": "Terdekat Dari Anda",

  /* ---------- Search Screen ---------- */
  "search.all_categories": "Semua",
  "search.categories": "Kategori",
  "search.cond_all": "Semua",
  "search.condition": "Kondisi Barang",
  "search.empty_desc": "Coba gunakan kata kunci lain atau pilih kategori yang berbeda.",
  "search.empty_title": "Barang Tidak Ditemukan",
  "search.placeholder": "Cari barang di sini...",
  "search.price_range": "Rentang Harga",
  "search.results": "Hasil Pencarian",

  /* ---------- Cart Screen ---------- */
  "cart.arrange_cod": "Membuat janji COD dengan penjual:",
  "cart.checkout_btn": "Checkout COD",
  "cart.confirm_title": "Buat Janji COD",
  "cart.empty_desc": "Belum ada barang yang ditambahkan ke keranjang belanja Anda.",
  "cart.empty_title": "Keranjang Anda Kosong",
  "cart.note_label": "Catatan:",
  "cart.note_placeholder": "Tulis catatan di sini...",
  "cart.remove_confirm_msg": "Apakah Anda yakin ingin menghapus barang ini dari keranjang?",
  "cart.remove_confirm_title": "Hapus Barang",
  "cart.seller_label": "Penjual",
  "cart.submit_cod": "Ajukan & Hubungi WA",
  "cart.success_toast": "Pemesanan COD berhasil dibuat.",
  "cart.title": "Keranjang Belanja",
  "cart.total": "Total:",

  /* ---------- Transaction History Screen ---------- */
  "history.btn_accept": "Terima",
  "history.btn_cancel": "Batalkan",
  "history.btn_complete": "Selesai COD",
  "history.btn_reject": "Tolak",
  "history.btn_wa": "WhatsApp",
  "history.buyer_label": "Pembeli:",
  "history.cancel_msg": "Apakah Anda yakin ingin membatalkan pemesanan ini?",
  "history.cancel_title": "Batalkan Pemesanan",
  "history.cod_notes": "Catatan COD",
  "history.complete_msg": "Apakah Anda menyatakan COD telah berhasil dan transaksi selesai?",
  "history.complete_title": "Transaksi Selesai",
  "history.empty_desc": "Riwayat transaksi Anda pada status ini masih kosong.",
  "history.empty_title": "Tidak Ada Transaksi",
  "history.not_found": "Transaksi tidak ditemukan.",
  "history.seller_label": "Penjual:",
  "history.tab_buyer": "Pembelian",
  "history.tab_seller": "Penjualan",
  "history.title": "Riwayat Transaksi",
  "history.total_label": "Total:",
  "history.trans_date": "Tanggal Transaksi",
  "history.trans_detail_title": "Detail Transaksi",
  "history.yes_cancel": "Ya, Batal",
  "history.yes_complete": "Ya, Selesai",

  /* ---------- My Items Screen ---------- */
  "myitems.btn_delete": "Hapus",
  "myitems.delete_confirm": "Apakah Anda yakin ingin menghapus {count} barang terpilih?",
  "myitems.delete_fail": "Gagal menghapus beberapa barang",
  "myitems.delete_success": "{count} barang berhasil dihapus",
  "myitems.delete_title": "Hapus Barang",
  "myitems.deselect_all": "Batal Semua",
  "myitems.empty_search": "Tidak ada barang yang cocok dengan pencarian Anda.",
  "myitems.empty_state": "Belum ada barang yang sesuai dengan filter atau status ini.",
  "myitems.empty_title": "Tidak Ada Barang",
  "myitems.error_price": "Batas minimum tidak boleh melebihi maksimum.",
  "myitems.item_status": "Status Barang",
  "myitems.select_all": "Pilih Semua",
  "myitems.selected": "terpilih",
  "myitems.sort_time": "Urutkan Berdasarkan Waktu",
  "myitems.start_selling": "Mulai Jual Barang",
  "myitems.tab_all": "Semua",
  "myitems.tab_available": "Tersedia",
  "myitems.tab_booked": "Dipesan",
  "myitems.tab_sold": "Terjual",
  "myitems.title": "Barang Saya",

  /* ---------- Post Item Screen ---------- */
  "postitem.back_to_detail": "Kembali ke Detail Barang",
  "postitem.cancel": "Batal",
  "postitem.category_label": "Kategori",
  "postitem.check_desc": "Poin yang tidak lulus wajib diberi catatan.",
  "postitem.check_done_desc": "Seluruh {count} poin telah Anda jawab.",
  "postitem.check_done_title": "Lembar Pengecekan Selesai!",
  "postitem.check_fail": "Tidak Lulus",
  "postitem.check_note_ph": "Jelaskan kondisi kekurangan ini...",
  "postitem.check_pass": "Lulus",
  "postitem.check_title": "Lembar Pengecekan Kondisi",
  "postitem.checksheet_tab": "Check Sheet",
  "postitem.cond_good": "Baik",
  "postitem.cond_poor": "Kurang",
  "postitem.cond_vg": "Sangat Baik",
  "postitem.condition_calc": "Dihitung otomatis berdasarkan Lembar Pengecekan.",
  "postitem.condition_no_cat": "Silakan pilih kategori terlebih dahulu.",
  "postitem.condition_none": "Kategori ini tidak memiliki lembar pengecekan.",
  "postitem.condition_title": "Kondisi Barang",
  "postitem.cover_badge": "SAMPUL",
  "postitem.description_label": "Deskripsi Barang",
  "postitem.description_placeholder": "Jelaskan kondisi barang, kekurangan, dll...",
  "postitem.detail": "Detail",
  "postitem.edit_title": "Edit Barang",
  "postitem.err_out_of_bounds": "Lokasi serah terima barang harus berada di dalam area kampus Politeknik Astra.",
  "postitem.fetching_location": "Melacak Lokasi Kampus...",
  "postitem.fill_checksheet": "Isi",
  "postitem.get_location": "Pilih Spot Pertemuan COD Kampus",
  "postitem.location_detail_label": "Detail Patokan Lokasi",
  "postitem.location_detail_placeholder": "Contoh: Lobi Gedung B, Depan Kantin",
  "postitem.location_subtitle": "Tentukan titik pertemuan",
  "postitem.location_title": "Lokasi Pertemuan",
  "postitem.map_coord_label": "Spot Lokasi Pertemuan COD Kampus",
  "postitem.media": "Media",
  "postitem.name_label": "Nama Barang",
  "postitem.name_placeholder": "Contoh: Jas Almamater Astra",
  "postitem.photo_subtitle": "Unggah maksimal 5 foto",
  "postitem.photo_title": "Foto Barang",
  "postitem.points_answered": "poin dijawab",
  "postitem.points_passed": "poin lulus",
  "postitem.points_passed_label": "Lulus",
  "postitem.post": "Tambah",
  "postitem.price_label": "Harga",
  "postitem.recorded_as": "Kondisi barang ini akan tercatat sebagai",
  "postitem.save_btn": "Simpan Perubahan",
  "postitem.select_category": "Pilih Kategori",
  "postitem.select_spot_modal_title": "Pilih Spot Pertemuan COD",
  "postitem.spot_set_toast": "Spot COD berhasil ditetapkan:",
  "postitem.spot_verified": "Spot Kampus Terverifikasi",
  "postitem.title": "Tambah Barang",
  "postitem.upload_desc": "Pilih gambar dari galeri atau kamera.\nJPG, JPEG, PNG. Maks. 5 MB.",
  "postitem.upload_photo": "Unggah Foto",
  "postitem.use_gps": "Gunakan Lokasi GPS HP Saat Ini",

  /* ---------- Detail Screen ---------- */
  "detail.checksheet_failed_count": "Terdapat {count} catatan minus dari penjual",
  "detail.checksheet_title": "Kondisi Fisik (Check Sheet)",
  "detail.contact_wa": "Hubungi via WA",
  "detail.delete_btn": "Hapus",
  "detail.delete_msg": "Apakah Anda yakin ingin menghapus barang ini secara permanen dari Thriftly?",
  "detail.delete_title": "Hapus Barang?",
  "detail.description": "Deskripsi",
  "detail.edit_item": "Edit Barang",
  "detail.hide_checks": "Sembunyikan Pengecekan",
  "detail.login_required_contact": "Silakan login terlebih dahulu untuk menghubungi penjual.",
  "detail.login_to_save": "Anda harus login untuk menyimpan barang ke keranjang belanja",
  "detail.meeting_location": "Lokasi Pertemuan",
  "detail.no_wa": "Nomor WA penjual tidak tersedia.",
  "detail.not_available": "Barang ini sudah tidak tersedia untuk dipesan.",
  "detail.open_wa_err": "Gagal membuka WhatsApp.",
  "detail.seller": "Penjual",
  "detail.view_checks": "Lihat Semua Pengecekan",

  /* ---------- Checksheet ---------- */
  "checksheet.c01_01": "Layar utuh (tidak ada retakan atau dead pixel)",
  "checksheet.c01_02": "Baterai bisa diisi daya (charging) dengan normal",
  "checksheet.c01_03": "Semua tombol fisik / keyboard / touch screen berfungsi responsif",
  "checksheet.c01_04": "Speaker dan mikrofon (audio) berfungsi normal",
  "checksheet.c01_05": "Port koneksi (USB, charger, HDMI, dll) berfungsi baik",
  "checksheet.c01_06": "Tidak ada kerusakan fisik pada bodi (retak/penyok parah)",
  "checksheet.c01_07": "Perangkat dapat menyala dan beroperasi normal (tidak bootloop/mati total)",
  "checksheet.c01_08": "Charger / kelengkapan kabel tersedia sesuai deskripsi",
  "checksheet.c02_01": "Semua halaman utuh dan lengkap (tidak ada yang sobek/hilang)",
  "checksheet.c02_02": "Cover depan dan belakang masih menempel dengan baik",
  "checksheet.c02_03": "Binding/jilid masih kuat (tidak lepas)",
  "checksheet.c02_04": "Tidak ada coretan berlebih yang menutupi teks utama",
  "checksheet.c02_05": "Halaman tidak berjamur, basah, atau berbau apek parah",
  "checksheet.c02_06": "Kualitas cetak/teks masih terbaca dengan jelas",
  "checksheet.c03_01": "Barang belum kedaluwarsa (untuk tinta/cat/spidol)",
  "checksheet.c03_02": "Fungsi utama berjalan baik (pulpen nyata, kalkulator nyala, dll)",
  "checksheet.c03_03": "Tidak ada bagian yang patah atau hilang yang mengganggu fungsi",
  "checksheet.c03_04": "Kondisi fisik masih bersih dan layak pakai",
  "checksheet.c04_01": "Tidak ada noda permanen yang mencolok",
  "checksheet.c04_02": "Tidak ada robekan, bolong, atau jahitan yang terlepas",
  "checksheet.c04_03": "Warna belum pudar secara signifikan",
  "checksheet.c04_04": "Ritsleting, kancing, atau pengikat lainnya berfungsi normal",
  "checksheet.c04_05": "Label/tag ukuran masih terbaca jelas",
  "checksheet.c04_06": "Tidak ada bau yang sulit dihilangkan (sudah dicuci bersih)",
  "checksheet.c05_01": "Komponen atau alat utuh, tidak ada yang pecah/retak (terutama kaca)",
  "checksheet.c05_02": "Semua kelengkapan bagian/aksesoris sesuai dengan deskripsi",
  "checksheet.c05_03": "Skala ukur (jika ada) masih terbaca jelas",
  "checksheet.c05_04": "Alat berfungsi secara mekanis/elektrik dengan baik",
  "checksheet.c05_05": "Tidak ada karat atau kontaminasi bahan kimia yang merusak alat",
  "checksheet.c06_01": "Tidak ada kerusakan struktural (patah, bengkok, retak parah)",
  "checksheet.c06_02": "Permukaan tidak memiliki goresan atau penyok yang merusak fungsi",
  "checksheet.c06_03": "Sambungan/engsel/baut masih kuat dan tidak longgar",
  "checksheet.c06_04": "Laci, pintu, atau roda (jika ada) dapat bergerak/dibuka dengan lancar",
  "checksheet.c06_05": "Tidak berjamur, bebas rayap, dan tidak ada noda membandel",
  "checksheet.c07_01": "Tidak ada kerusakan struktural (patah, retak, bengkok)",
  "checksheet.c07_02": "Semua bagian lengkap sesuai dengan kelengkapan awal",
  "checksheet.c07_03": "Material/bahan (kain, karet, besi) masih kuat dan layak pakai",
  "checksheet.c07_04": "Tidak ada karat berlebihan yang mengganggu fungsi alat",
  "checksheet.c07_05": "Berfungsi normal sesuai kegunaannya",
  "checksheet.c07_06": "Ukuran/spesifikasi persis seperti yang tertera di deskripsi",

  /* ---------- Profile Screen ---------- */
  "profile.account": "Akun",
  "profile.account_center": "Pusat Akun",
  "profile.cancel": "Batal",
  "profile.desc_account": "Kelola profil & keamanan",
  "profile.desc_history": "Pembelian & penjualan",
  "profile.desc_my_items": "Kelola listing barang",
  "profile.desc_notification": "Peringatan & pesan",
  "profile.lang_english": "English",
  "profile.lang_indonesia": "Indonesia",
  "profile.language": "Bahasa",
  "profile.logout": "Keluar",
  "profile.logout_confirm_message": "Apakah Anda yakin ingin keluar dari akun?",
  "profile.logout_confirm_title": "Konfirmasi Keluar",
  "profile.menu_notification": "Notifikasi",
  "profile.my_orders": "Riwayat Transaksi",
  "profile.preferences": "Preferensi",
  "profile.saved_items": "Barang Saya",
  "profile.yes_logout": "Ya, Keluar",

  /* ---------- Account Center Screen ---------- */
  "account.campus_identity": "Identitas Kemahasiswaan",
  "account.cancel": "Batal",
  "account.change_password": "Ubah Kata Sandi",
  "account.change_password_title": "Ubah Kata Sandi",
  "account.confirm_password": "Konfirmasi Kata Sandi Baru",
  "account.confirm_password_placeholder": "Ulangi sandi baru",
  "account.email": "Email",
  "account.full_name": "Nama Lengkap",
  "account.name_placeholder": "Masukkan nama lengkap",
  "account.new_password": "Kata Sandi Baru",
  "account.new_password_placeholder": "Minimal 8 karakter",
  "account.nim": "NIM",
  "account.old_password": "Kata Sandi Saat Ini",
  "account.old_password_placeholder": "Masukkan sandi lama",
  "account.phone": "Nomor Telepon",
  "account.phone_placeholder": "contoh: 08123456789",
  "account.public_info": "Informasi Publik",
  "account.save": "Simpan",
  "account.save_password": "Simpan Sandi",
  "account.title": "Pusat Akun",

  /* ---------- Notification Screen ---------- */
  "notification.delete_confirm": "Tindakan ini tidak dapat dibatalkan. %{count} notifikasi yang dipilih akan dihapus secara permanen dari riwayat Anda.",
  "notification.delete_success": "Notifikasi berhasil dihapus",
  "notification.delete_title": "Hapus Notifikasi",
  "notification.empty_desc": "Anda belum memiliki notifikasi baru saat ini.",
  "notification.empty_title": "Tidak Ada Notifikasi",
  "notification.mark_all_read": "Tandai Semua Dibaca",
  "notification.mark_read": "Tandai Dibaca",
  "notification.perm_allow": "Izinkan",
  "notification.perm_deny": "Tolak",
  "notification.perm_msg": "THRFTLY butuh izin notifikasi agar Anda tidak ketinggalan update pesanan dan pesan. Lanjutkan?",
  "notification.perm_title": "Aktifkan Notifikasi",
  "notification.title": "Notifikasi",

  /* ---------- Notification Types ---------- */
  "notif_type.accepted_msg": "%{name} telah menerima pesanan COD Anda. Silakan hubungi via WhatsApp.",
  "notif_type.accepted_title": "Pesanan Diterima",
  "notif_type.cancelled_msg": "%{name} telah membatalkan pesanan COD.",
  "notif_type.cancelled_title": "Pesanan Dibatalkan",
  "notif_type.completed_msg": "Transaksi COD telah dinyatakan selesai.",
  "notif_type.completed_title": "Transaksi Selesai",
  "notif_type.new_order_msg": "%{name} telah mengajukan pesanan COD baru untuk produk Anda.",
  "notif_type.new_order_title": "Pesanan COD Baru",
  "notif_type.rejected_msg": "%{name} telah menolak pesanan COD Anda.",
  "notif_type.rejected_title": "Pesanan Ditolak",

  /* ---------- Categories ---------- */
  "category.cat01": "Elektronik & Gadget",
  "category.cat02": "Buku & Modul",
  "category.cat03": "Alat Tulis & Stationary",
  "category.cat04": "Pakaian & Atribut Kampus",
  "category.cat05": "Peralatan Praktikum & Lab",
  "category.cat06": "Furnitur & Perlengkapan Kos",
  "category.cat07": "Olahraga & Hobi",

  /* ---------- API Messages ---------- */
  "api.ERR_AUTH_FAILED": "Autentikasi gagal",
  "api.ERR_BAD_CREDENTIALS": "NIM/Email atau Password salah",
  "api.ERR_EMAIL_EXISTS": "Email sudah digunakan",
  "api.ERR_EMAIL_FORMAT": "Email harus sesuai dengan NIM Anda",
  "api.ERR_INVALID_OTP": "Kode OTP salah",
  "api.ERR_NIM_EXISTS": "NIM sudah terdaftar",
  "api.ERR_OTP_EXPIRED": "Kode OTP telah kedaluwarsa",
  "api.ERR_OUT_OF_BOUNDS": "Lokasi serah terima barang harus berada di dalam area kampus Politeknik Astra.",
  "api.ERR_USER_NOT_FOUND": "NIM atau Email tidak terdaftar",
  "api.SUCCESS_LOGIN": "Masuk berhasil",
  "api.SUCCESS_OTP_SENT": "Kode OTP berhasil dikirim",
  "api.SUCCESS_OTP_VALID": "Kode OTP valid",
  "api.SUCCESS_PASSWORD_RESET": "Kata sandi berhasil diperbarui",
  "api.SUCCESS_REGISTER": "Pendaftaran berhasil! Silakan masuk.",

  /* ---------- Status Labels ---------- */
  "status.accepted": "COD Berlangsung",
  "status.available": "Tersedia",
  "status.booked": "Dipesan",
  "status.cancelled": "Dibatalkan",
  "status.completed": "Selesai",
  "status.pending": "Menunggu",
  "status.rejected": "Ditolak",
  "status.sold": "Terjual",

  /* ---------- Navigation ---------- */
  "nav.cart": "Keranjang",
  "nav.home": "Beranda",
  "nav.profile": "Profil",
  "nav.search": "Cari",


  /* ---------- Common ---------- */
  "common.all": "Semua",
  "common.allow": "Izinkan",
  "common.apply_filter": "Terapkan Filter",
  "common.cancel": "Batal",
  "common.category": "Kategori",
  "common.close": "Tutup",
  "common.delete": "Hapus",
  "common.deny": "Tolak",
  "common.empty_search_result": "Tidak ada hasil yang ditemukan.",
  "common.error": "Gagal menyimpan perubahan",
  "common.filter": "Filter",
  "common.max": "Max",
  "common.min": "Min",
  "common.newest": "Terbaru",
  "common.oldest": "Terlama",
  "common.read_more": "Selengkapnya",
  "common.required": "Wajib diisi",
  "common.sort": "Urutkan",
  "common.success": "Perubahan berhasil disimpan!",
  "common.yes": "Ya",
  "common.yes_delete": "Ya, Hapus",

  /* ---------- Transaction History Screen ---------- */
  "history.update_fail": "Gagal memperbarui transaksi",
  "history.no_phone": "Nomor telepon tidak tersedia.",
  "history.wa_fail": "Gagal membuka WhatsApp.",
  "history.wa_template": "Halo %{name},\nsaya ingin menghubungi mengenai pesanan COD di Thriftly:\n\n%{items}\n\n*Total:* %{total}\nBagaimana kelanjutan COD kita?",
  "history.notif_update_title": "Update Transaksi",
  "history.notif_update_msg": "Status transaksi berhasil diperbarui.",
  "history.notif_accepted_title": "Pesanan Diterima",
  "history.notif_accepted_msg": "Anda telah menerima pesanan COD ini.",
  "history.notif_rejected_title": "Pesanan Ditolak",
  "history.notif_rejected_msg": "Anda telah menolak pesanan COD ini.",
  "history.notif_cancelled_title": "Pesanan Dibatalkan",
  "history.notif_cancelled_msg": "Pesanan COD telah dibatalkan.",
  "history.notif_completed_title": "Transaksi Selesai",
  "history.notif_completed_msg": "Transaksi COD telah dinyatakan selesai.",
  "history.title": "Riwayat Transaksi",
  "history.tab_buyer": "Pembelian",
  "history.tab_seller": "Penjualan",
  "history.empty_title": "Tidak Ada Transaksi",
  "history.empty_desc": "Riwayat transaksi Anda pada status ini masih kosong.",
  "history.seller_label": "Penjual:",
  "history.buyer_label": "Pembeli:",
  "cart.total": "Total Harga:",
  "history.total_label": "Total Harga:",
  "history.btn_cancel": "Batalkan",
  "history.btn_reject": "Tolak",
  "history.btn_accept": "Terima",
  "history.btn_wa": "WhatsApp",
  "history.btn_complete": "Selesai COD",
  "history.cancel_title": "Batalkan Pemesanan",
  "history.cancel_msg": "Apakah Anda yakin ingin membatalkan pemesanan ini?",
  "history.complete_title": "Transaksi Selesai",
  "history.complete_msg": "Apakah Anda menyatakan COD telah berhasil dan transaksi selesai?",
  "history.yes_cancel": "Ya, Batal",
  "history.yes_complete": "Ya, Selesai",
  "history.trans_date": "Tanggal Transaksi",
  "history.trans_detail_title": "Detail Transaksi",
  "history.not_found": "Transaksi tidak ditemukan.",
  "history.cod_notes": "Catatan COD",

  /* ---------- Detail Screen ---------- */
  "detail.login_to_save": "Anda harus login untuk menyimpan barang ke keranjang belanja",
  "detail.contact_wa": "Hubungi via WA",
  "detail.edit_item": "Edit Barang",
  "detail.delete_title": "Hapus Barang?",
  "detail.delete_msg": "Apakah Anda yakin ingin menghapus barang ini secara permanen dari Thriftly?",
  "detail.delete_btn": "Hapus",
  "detail.meeting_location": "Lokasi Pertemuan",
  "detail.view_checks": "Lihat Semua Pengecekan",
  "detail.hide_checks": "Sembunyikan Pengecekan",
  "detail.description": "Deskripsi",
  "detail.seller": "Penjual",
  "detail.login_required_contact": "Silakan login terlebih dahulu untuk menghubungi penjual.",
  "detail.no_wa": "Nomor WA penjual tidak tersedia.",
  "detail.not_available": "Barang ini sudah tidak tersedia untuk dipesan.",
  "detail.checksheet_title": "Kondisi Fisik (Check Sheet)",
  "detail.checksheet_failed_count": "Terdapat {count} catatan minus dari penjual",
  "detail.open_wa_err": "Gagal membuka WhatsApp.",
  "cart.item_unavailable_btn": "Sudah Dipesan",
  "cart.item_sold_btn": "Sudah Terjual"
};